server:
  name: "user"
  addr: "127.0.0.1:8301"
zap:
  debugFileName: "/newsCenter/logs/debug/newsCenter-debug.logs"
  infoFileName: "/newsCenter/logs/info/newsCenter-info.logs"
  warnFileName: "/newsCenter/logs/error/newsCenter-error.logs"
  maxSize: 500,
  maxAge: 28,
  MaxBackups: 3,
etcd:
  addr:
    - "127.0.0.1:2379"
mysql:
  username: root
  password: root
  host: 127.0.0.1
  port: 3309
  db: newsCenter
redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0
grpc:
  addr: "127.0.0.1:8302"
  name: "user"
  version: "1.0.0"
  weight: 2
jwt:
  accessExp: 7
  refreshExp: 14
  accessSecret: newsCenter
  refreshSecret: newsCenter